import { LegalPage, LegalCallout, LegalList, LegalListItem, type LegalSection } from '../components/LegalPage'

const SECTIONS: LegalSection[] = [
  {
    id: 'what-dojo-is',
    label: 'What dojo is',
    body: (
      <>
        <p>
          Dojo is a daily practice tool for software engineers. It assigns you a timed kata,
          evaluates your response with an AI sensei, and gives you a verdict.
        </p>
        <p>
          Dojo is open-source software that anyone can run. This instance is run by its
          operator, not by the dojo project, and these terms describe how it works. Access is by
          invitation: the operator issues the invitation links.
        </p>
      </>
    ),
  },
  {
    id: 'what-you-agree-to',
    label: 'What you agree to',
    body: (
      <>
        <p>By using dojo, you agree to:</p>
        <LegalList>
          <LegalListItem>Use a real GitHub account that represents you.</LegalListItem>
          <LegalListItem>
            Complete kata honestly — the practice only works if it's real.
          </LegalListItem>
          <LegalListItem>
            Not abuse the API, attempt to extract evaluation logic, or interfere with other
            practitioners' sessions.
          </LegalListItem>
          <LegalListItem>
            Accept that the sensei's evaluation is generated by an LLM and may occasionally be
            imperfect.
          </LegalListItem>
        </LegalList>
      </>
    ),
  },
  {
    id: 'honor-code',
    label: 'The honor code',
    body: (
      <>
        <LegalCallout>
          <p className="text-base font-medium leading-relaxed">
            The timer doesn't pause. The kata is yours. No AI during the kata.
          </p>
        </LegalCallout>
        <p>
          These are not enforced technically — they're trusted. The dojo works because
          practitioners choose to practice honestly. If that changes, the practice becomes
          meaningless regardless of the verdict.
        </p>
      </>
    ),
  },
  {
    id: 'termination',
    label: 'Account termination',
    body: (
      <>
        <p>
          The operator of this instance can close your account if you violate these terms. You can
          leave at any time.
        </p>
      </>
    ),
  },
  {
    id: 'license',
    label: 'Open source license',
    body: (
      <>
        <p>
          Dojo is open source under the MIT License. The source code is available on GitHub.
          The kata content and sensei prompts are part of the codebase — they are not
          secret.
        </p>
        <p>
          You can read, fork, and run your own instance, kata catalog included. The license asks
          only that its copyright notice travels with the code.
        </p>
      </>
    ),
  },
  {
    id: 'changes',
    label: 'Changes to these terms',
    body: (
      <p>
        The operator may update these terms. Changes will be reflected on this page with an
        updated effective date.
      </p>
    ),
  },
  {
    id: 'contact',
    label: 'Contact',
    body: (
      <p>
        Questions about this instance go to its operator. Questions about the dojo software
        itself: open an issue on GitHub.
      </p>
    ),
  },
]

export function TermsPage() {
  return <LegalPage title="Terms of Service" lastUpdated="2026-09-28" sections={SECTIONS} />
}
