import { useEffect, useState } from 'react'
import { PublicPageLayout } from '../components/PublicPageLayout'

const sections = [
  { id: 'what-dojo-is', label: 'What dojo is' },
  { id: 'what-you-agree-to', label: 'What you agree to' },
  { id: 'honor-code', label: 'The honor code' },
  { id: 'termination', label: 'Account termination' },
  { id: 'license', label: 'Open source license' },
  { id: 'changes', label: 'Changes' },
  { id: 'contact', label: 'Contact' },
]

export function TermsPage() {
  const [activeSection, setActiveSection] = useState(sections[0]!.id)

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id)
          }
        }
      },
      { rootMargin: '-20% 0px -70% 0px' }
    )

    for (const section of sections) {
      const el = document.getElementById(section.id)
      if (el) observer.observe(el)
    }

    return () => observer.disconnect()
  }, [])

  return (
    <PublicPageLayout>
      <div className="max-w-5xl mx-auto px-8 py-16">
        <h1 className="font-mono text-2xl md:text-3xl text-primary mb-2">Terms of Service</h1>
        <p className="text-secondary text-sm mb-2">Plain language. No surprises.</p>
        <p className="text-muted text-xs font-mono mb-12">Effective: March 2026</p>

        <div className="flex gap-12">
          {/* Sidebar */}
          <aside className="hidden lg:block w-48 shrink-0">
            <div className="sticky top-8 space-y-1">
              {sections.map(({ id, label }) => (
                <a
                  key={id}
                  href={`#${id}`}
                  className={`block text-xs font-mono py-1.5 pl-3 border-l-2 transition-colors ${
                    activeSection === id
                      ? 'border-accent text-primary'
                      : 'border-transparent text-muted hover:text-secondary'
                  }`}
                >
                  {label}
                </a>
              ))}
            </div>
          </aside>

          {/* Content */}
          <div className="flex-1 max-w-2xl space-y-12">
            {/* Mobile nav */}
            <div className="flex flex-wrap gap-2 lg:hidden">
              {sections.map(({ id, label }) => (
                <a key={id} href={`#${id}`} className="text-xs font-mono text-muted hover:text-secondary">
                  {label}
                </a>
              ))}
            </div>

            <section id="what-dojo-is">
              <h2 className="font-mono text-lg text-primary mb-4">What dojo is</h2>
              <div className="text-secondary text-sm leading-relaxed space-y-3">
                <p>
                  Dojo is a daily practice tool for software engineers. It assigns you a timed exercise (a "kata"),
                  evaluates your response using an AI sensei, and gives you a verdict.
                </p>
                <p>
                  The product is invite-only during its early phase. Access is granted through invitation
                  links created by existing practitioners or by the creator.
                </p>
              </div>
            </section>

            <section id="what-you-agree-to">
              <h2 className="font-mono text-lg text-primary mb-4">What you agree to</h2>
              <div className="text-secondary text-sm leading-relaxed space-y-3">
                <p>By using dojo, you agree to:</p>
                <ul className="list-none space-y-2 pl-0">
                  <li className="flex gap-2">
                    <span className="text-accent shrink-0">→</span>
                    <span>Use a real GitHub account that represents you</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-accent shrink-0">→</span>
                    <span>Complete kata honestly — the practice only works if it's real</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-accent shrink-0">→</span>
                    <span>Not abuse the API, attempt to extract evaluation logic, or interfere with other users' sessions</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-accent shrink-0">→</span>
                    <span>Accept that the sensei's evaluation is generated by an LLM and may occasionally be imperfect</span>
                  </li>
                </ul>
              </div>
            </section>

            <section id="honor-code">
              <h2 className="font-mono text-lg text-primary mb-4">The honor code</h2>
              <div className="border-l-[3px] border-accent bg-surface rounded-r-md p-5">
                <p className="text-primary text-sm leading-relaxed font-medium mb-3">
                  The timer doesn't pause. The kata is yours. No AI during the exercise.
                </p>
                <p className="text-secondary text-sm leading-relaxed">
                  These are not enforced technically — they're trusted. The dojo works because practitioners
                  choose to practice honestly. If that changes, the practice becomes meaningless regardless
                  of the verdict.
                </p>
              </div>
            </section>

            <section id="termination">
              <h2 className="font-mono text-lg text-primary mb-4">Account termination</h2>
              <div className="text-secondary text-sm leading-relaxed space-y-3">
                <p>
                  We can terminate your account if you violate these terms. You can leave at any time.
                </p>
                <p>
                  If your account is terminated, your session data may be retained for integrity
                  of the leaderboard, but your profile will no longer be publicly visible.
                </p>
              </div>
            </section>

            <section id="license">
              <h2 className="font-mono text-lg text-primary mb-4">Open source license</h2>
              <div className="text-secondary text-sm leading-relaxed space-y-3">
                <p>
                  Dojo is open source under the MIT License. The source code is available on GitHub.
                  The exercise content and sensei prompts are part of the codebase — they are not secret.
                </p>
                <p>
                  "Open source" means you can read, fork, and learn from the code. It does not
                  mean you can run a competing instance using our exercise catalog without
                  attribution.
                </p>
              </div>
            </section>

            <section id="changes">
              <h2 className="font-mono text-lg text-primary mb-4">Changes to these terms</h2>
              <div className="text-secondary text-sm leading-relaxed space-y-3">
                <p>
                  We may update these terms. Changes will be reflected on this page with an updated
                  effective date. If a change is significant, we'll note it in the changelog.
                </p>
              </div>
            </section>

            <section id="contact">
              <h2 className="font-mono text-lg text-primary mb-4">Contact</h2>
              <div className="text-secondary text-sm leading-relaxed space-y-3">
                <p>
                  Questions about these terms? Open an issue on GitHub or reach out via the
                  channels listed on the open source page.
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </PublicPageLayout>
  )
}
