import { LegalPage, LegalCallout, LegalList, LegalListItem, type LegalSection } from '../components/LegalPage'

const SECTIONS: LegalSection[] = [
  {
    id: 'what-dojo-is',
    label: 'What dojo is',
    body: (
      <>
        <p>
          Dojo is a daily practice tool for software engineers. It assigns you a timed exercise
          (a "kata"), evaluates your response with an AI sensei, and gives you a verdict.
        </p>
        <p>
          The product is invite-only during its early phase. Access is granted through
          invitation links created by existing practitioners or by the creator.
        </p>
      </>
    ),
  },
  {
    id: 'what-you-agree-to',
    label: 'What you agree to',
    body: (
      <>
        <p>By using dojo, you agree to:</p>
        <LegalList>
          <LegalListItem>Use a real GitHub account that represents you.</LegalListItem>
          <LegalListItem>
            Complete kata honestly — the practice only works if it's real.
          </LegalListItem>
          <LegalListItem>
            Not abuse the API, attempt to extract evaluation logic, or interfere with other
            practitioners' sessions.
          </LegalListItem>
          <LegalListItem>
            Accept that the sensei's evaluation is generated by an LLM and may occasionally be
            imperfect.
          </LegalListItem>
        </LegalList>
      </>
    ),
  },
  {
    id: 'honor-code',
    label: 'The honor code',
    body: (
      <>
        <LegalCallout>
          <p className="text-[15px] font-medium leading-relaxed">
            The timer doesn't pause. The kata is yours. No AI during the exercise.
          </p>
        </LegalCallout>
        <p>
          These are not enforced technically — they're trusted. The dojo works because
          practitioners choose to practice honestly. If that changes, the practice becomes
          meaningless regardless of the verdict.
        </p>
      </>
    ),
  },
  {
    id: 'termination',
    label: 'Account termination',
    body: (
      <>
        <p>We can terminate your account if you violate these terms. You can leave at any time.</p>
        <p>
          If your account is terminated, your session data may be retained for integrity of the
          leaderboard, but your profile will no longer be publicly visible.
        </p>
      </>
    ),
  },
  {
    id: 'license',
    label: 'Open source license',
    body: (
      <>
        <p>
          Dojo is open source under the MIT License. The source code is available on GitHub.
          The exercise content and sensei prompts are part of the codebase — they are not
          secret.
        </p>
        <p>
          "Open source" means you can read, fork, and learn from the code. It does not mean
          you can run a competing instance using our exercise catalog without attribution.
        </p>
      </>
    ),
  },
  {
    id: 'changes',
    label: 'Changes to these terms',
    body: (
      <p>
        We may update these terms. Changes will be reflected on this page with an updated
        effective date. If a change is significant, we'll note it in the changelog.
      </p>
    ),
  },
  {
    id: 'contact',
    label: 'Contact',
    body: (
      <p>
        Questions about these terms? Open an issue on GitHub or reach out via the channels
        listed on the open source page.
      </p>
    ),
  },
]

export function TermsPage() {
  return <LegalPage title="Terms of Service" lastUpdated="2026-04-15" sections={SECTIONS} />
}
